# Generated by Django 3.1.1 on 2020-09-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200926_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='default.png', upload_to='blog-cover-photos/%Y/%m/%d/'),
        ),
    ]
