# Generated by Django 3.1.1 on 2020-09-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200927_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='avatar',
            field=models.ImageField(default='author-avatars/default.jpeg', upload_to='author-avatars/%Y'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='blog-cover-photos/default.png', upload_to='blog-cover-photos/%Y/%m/%d/'),
        ),
    ]
